<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Authors>Wilderness Labs, Inc</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <TargetFramework>net10.0</TargetFramework>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>icon.png</PackageIcon>
    <AssemblyName>Meadow.Logging</AssemblyName>
    <Company>Wilderness Labs, Inc</Company>
    <PackageProjectUrl>https://github.com/WildernessLabs/Meadow.Logging</PackageProjectUrl>
    <PackageId>Meadow.Logging</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Logging</RepositoryUrl>
    <PackageTags>Meadow</PackageTags>
    <Description>Wilderness Labs ultra-lightweight logging library</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Meadow</RootNamespace>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Update="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
