name: Develop Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Meadow.Logging
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c Release Source/Meadow.Logging/Meadow.Logging.sln
