name: Main Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Meadow.Logging
      uses: actions/checkout@v3
      with:
        path: Meadow.Logging

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c Release Meadow.Logging/Source/Meadow.Logging/Meadow.Logging.sln
